"""typo in review table

Revision ID: 49f91249fcf8
Revises: 4a70629653e5
Create Date: 2021-11-17 17:09:22.593293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49f91249fcf8'
down_revision = '4a70629653e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('overall_star_rating', sa.Integer(), nullable=True))
    op.drop_column('review', 'overall_start_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('overall_start_rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('review', 'overall_star_rating')
    # ### end Alembic commands ###
