"""added review table

Revision ID: 645bd97865b5
Revises: 31b380863339
Create Date: 2021-11-11 16:34:23.902009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645bd97865b5'
down_revision = '31b380863339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_table('review')
    # ### end Alembic commands ###
