"""added zipcode to landlord

Revision ID: 8a4f73f6f4cb
Revises: e60a13ccab72
Create Date: 2021-11-24 15:18:33.542672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4f73f6f4cb'
down_revision = 'e60a13ccab72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord', sa.Column('zipcode', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlord', 'zipcode')
    # ### end Alembic commands ###
