"""added foriegn keys to tables

Revision ID: e60a13ccab72
Revises: 49f91249fcf8
Create Date: 2021-11-20 17:51:09.076185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e60a13ccab72'
down_revision = '49f91249fcf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord', sa.Column('first_name', sa.String(length=40), nullable=True))
    op.add_column('landlord', sa.Column('last_name', sa.String(length=40), nullable=True))
    op.drop_constraint('landlord_ibfk_1', 'landlord', type_='foreignkey')
    op.drop_column('landlord', 'property_id')
    op.add_column('property', sa.Column('landlord_id', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('city', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'property', 'landlord', ['landlord_id'], ['id'])
    op.add_column('review', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'property', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'property_id')
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'city')
    op.drop_column('property', 'landlord_id')
    op.add_column('landlord', sa.Column('property_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('landlord_ibfk_1', 'landlord', 'property', ['property_id'], ['id'])
    op.drop_column('landlord', 'last_name')
    op.drop_column('landlord', 'first_name')
    # ### end Alembic commands ###
